title: Kirti Bajaj
logo: https://github.com/KIRTIBAJAJ2002/portfolio/blob/main/Picsart_24-01-15_20-38-14-501.png?raw=true
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
